task:
  name: wti_case1_HPT
dataset:
  path: data/df.csv
  target_col: Com_CrudeOil
  dt_col: dt
  hist_exog_cols:
  - Com_Gasoline
  - Com_LME_Zn_Inv
  - Com_OrangeJuice
  - Com_Cheese
  - Bonds_BRZ_1Y
  - Idx_OVX
  - Com_Cu_Gold_Ratio
  - Com_LME_Sn_Inv
  - Idx_CSI300
  - Com_LME_Zn_Spread
  - Bonds_CHN_Spread_5Y_2Y
  - Com_LME_Al_Spread
  - Bonds_CHN_Spread_2Y_1Y
  - Com_Oil_Spread
  - Bonds_CHN_Spread_10Y_5Y
  futr_exog_cols: []
  static_exog_cols: []
runtime:
  random_seed: 1
  opt_n_trial: 20
training:
  train_protocol: expanding_window_tscv
  season_length: 52
  batch_size: 32
  valid_batch_size: 32
  windows_batch_size: 1024
  inference_windows_batch_size: 1024
  max_steps: 1000
  val_check_steps: 100
  val_size: 8
  early_stop_patience_steps: 5
  loss: mse
cv:
  horizon: 8
  step_size: 8
  n_windows: 5
  gap: 0
  max_train_size: null
  overlap_eval_policy: by_cutoff_mean
scheduler:
  gpu_ids:
  - 0
  - 1
  max_concurrent_jobs: 2
  worker_devices: 1
residual:
  enabled: true
  model: xgboost
  params: {}
jobs:
- model: PatchTST
  params: {}
- model: DLinear
  params: {}
- model: Naive
  params: {}
- model: iTransformer
  params: {}
- model: LSTM
  params: {}
- model: NHITS
  params: {}
