runtime:
  random_seed: 1
  opt_study_count: 2
  opt_n_trial: 2
training:
  input_size: 64
  batch_size: 32
  valid_batch_size: 8
  windows_batch_size: 64
  inference_windows_batch_size: 64
  max_steps: 800
  val_size: 16
  scaler_type: robust
  val_check_steps: 4
  min_steps_before_early_stop: 200
  model_step_size: 1
  early_stop_patience_steps: 8
  loss: mse
  optimizer:
    name: adamw
    kwargs: {}
  lr_scheduler:
    name: ReduceLROnPlateau
    max_lr: 0.0003
    mode: min
    factor: 0.5
    patience: 2
    threshold: 0.001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0.0
    eps: 1.0e-06
cv:
  gap: 0
  horizon: 2
  step_size: 4
  n_windows: 4
  max_train_size: null
  overlap_eval_policy: by_cutoff_mean
scheduler:
  gpu_ids:
  - 0
  max_concurrent_jobs: 1
  worker_devices: 1
