task:
  name: baseline_wti_test
dataset:
  path: data/df.csv
  target_col: Com_CrudeOil
  dt_col: dt
  hist_exog_cols:
  - Com_LME_Ni_Cash
  - Com_LME_Cu_Cash
  - Com_LME_Al_Cash
  - Com_LME_Pb_Cash
  - Com_LME_Sn_Cash
  - Com_LME_Zn_Cash
  - Com_LME_Ni_Spread
  - Com_LME_Cu_Spread
  - Com_LME_Al_Spread
  - Com_LME_Pb_Spread
  - Com_LME_Sn_Spread
  - Com_LME_Zn_Spread
  - Com_LME_Ni_Inv
  - Com_LME_Cu_Inv
  - Com_LME_Al_Inv
  - Com_LME_Pb_Inv
  - Com_LME_Sn_Inv
  - Com_LME_Zn_Inv
  - EX_USD_CNY
  - EX_USD_KRW
  - EX_USD_JPY
  - EX_AUD_USD
  - EX_USD_BRL
  - EX_INR_USD
  - Idx_DxyUSD
  - Idx_SnP500
  - Idx_SnPVIX
  - Bonds_MOVE
  - Idx_GVZ
  - Idx_OVX
  - Com_BloombergCommodity_BCOM
  - Com_LMEX
  - Idx_CH50
  - Idx_CSI300
  - Idx_Shanghai50
  - Idx_Shanghai
  - Idx_HangSeng
  - Idx_SnPGlobal1200
  - Bonds_CHN_30Y
  - Bonds_CHN_20Y
  - Bonds_CHN_10Y
  - Bonds_CHN_5Y
  - Bonds_CHN_2Y
  - Bonds_CHN_1Y
  - Bonds_US_10Y
  - Bonds_US_2Y
  - Bonds_US_1Y
  - Bonds_US_3M
  - Bonds_AUS_10Y
  - Bonds_AUS_1Y
  - Bonds_BRZ_10Y
  - Bonds_BRZ_1Y
  - Bonds_IND_10Y
  - Bonds_IND_1Y
  - Bonds_KOR_10Y
  - Bonds_KOR_1Y
  - Com_Gasoline
  - Com_NaturalGas
  - Com_Uranium
  - Com_HRC_Steel
  - Com_Iron_Ore
  - Com_Coal
  - Com_Steel
  - Com_Gold
  - Com_Silver
  - Com_Soybeans
  - Com_Wheat
  - Com_Rice
  - Com_Barley
  - Com_Cheese
  - Com_Corn
  - Com_Oat
  - Com_Sugar
  - Com_Cocoa
  - Com_Milk
  - Com_OrangeJuice
  - Com_Coffee
  - Com_SunflowerOil
  - Com_PalmOil
  - Com_Canola
  - Com_Cotton
  - Com_Wool
  - Com_Lumber
  - BS_Core_Index_A
  - BS_Core_Index_B
  - BS_Core_Index_C
  - BS_Core_Index_Integrated
  - Com_Oil_Spread
  futr_exog_cols: []
  static_exog_cols: []
runtime:
  random_seed: 1
training:
  train_protocol: expanding_window_tscv
  input_size: 64
  season_length: 52
  batch_size: 32
  valid_batch_size: 32
  windows_batch_size: 1024
  inference_windows_batch_size: 1024
  learning_rate: 0.001
  max_steps: 3
  val_size: 12
  val_check_steps: 100
  early_stop_patience_steps: -1
  loss: mse
cv:
  horizon: 8
  step_size: 4
  n_windows: 1
  gap: 0
  max_train_size: null
  overlap_eval_policy: by_cutoff_mean
scheduler:
  gpu_ids:
  - 0
  - 1
  max_concurrent_jobs: 2
  worker_devices: 1
residual:
  enabled: false
  model: xgboost
  params: {}
jobs:
- model: LSTM
  params: {}
- model: NHITS
  params: {}
- model: DLinear
  params: {}
- model: TFT
  params: {}
- model: Autoformer
  params: {}
- model: FEDformer
  params: {}
- model: PatchTST
  params: {}
- model: iTransformer
  params: {}
- model: TimeMixer
  params: {}
- model: TimesNet
  params: {}
- model: NonstationaryTransformer
  params: {}
- model: SMamba
  params: {}
- model: Naive
  params: {}
