task:
  name: semi_test
dataset:
  path: ../df.csv
  target_col: Com_CrudeOil
  dt_col: dt
  hist_exog_cols:
  - Com_BrentCrudeOil
  - Com_Gasoline
  - Idx_DxyUSD
  - EX_USD_CNY
  - Idx_SnP500
  - Idx_SnPVIX
  - Idx_CSI300
  - Bonds_US_10Y
  - Bonds_US_2Y
  - Com_LME_Index
  - Com_Iron_Ore
  futr_exog_cols: []
  static_exog_cols: []
training:
  val_check_steps: 100
  early_stop_patience_steps: 5
  loss: mse
cv:
  horizon: 12
  step_size: 8
  n_windows: 24
  max_train_size: null
scheduler:
  gpu_ids:
  - 0
  - 1
residual:
  enabled: true
  model: xgboost
  params:
    n_estimators: 64
    max_depth: 3
    learning_rate: 0.1
    subsample: 1.0
    colsample_bytree: 1.0
jobs:
- model: TFT
  params:
    hidden_size: 128
- model: VanillaTransformer
  params:
    hidden_size: 128
    dropout: 0.05
    scaler_type: identity
- model: Informer
  params:
    hidden_size: 128
    factor: 3
    dropout: 0.05
    scaler_type: identity
- model: Autoformer
  params:
    hidden_size: 128
    factor: 3
    dropout: 0.05
    scaler_type: identity
- model: PatchTST
  params:
    hidden_size: 128
    n_heads: 16
    encoder_layers: 3
    patch_len: 16
    dropout: 0.2
    scaler_type: identity
- model: LSTM
  params:
    encoder_hidden_size: 128
    decoder_hidden_size: 128
- model: NHITS
  params:
    mlp_units:
    - - 64
      - 64
    - - 64
      - 64
    - - 64
      - 64
    n_pool_kernel_size:
    - 2
    - 2
    - 1
    n_freq_downsample:
    - 4
    - 2
    - 1
    dropout_prob_theta: 0.0
    activation: ReLU
- model: iTransformer
  params:
    hidden_size: 128
    n_heads: 8
    e_layers: 2
    d_ff: 256
- model: Naive
  params: {}
