task:
  name: wti_case3_bs
dataset:
  path: data/df.csv
  target_col: Com_CrudeOil
  dt_col: dt
  hist_exog_cols:
  - Com_Gasoline
  - Com_BloombergCommodity_BCOM
  - Com_LME_Ni_Cash
  - Com_Coal
  - Com_LME_Al_Cash
  - Com_LMEX
  - Bonds_KOR_10Y
  - Com_LME_Ni_Inv
  - BS_Core_Index_A
  - BS_Core_Index_B
  - BS_Core_Index_C
  - BS_Core_Index_Integrated
  futr_exog_cols: []
  static_exog_cols: []
residual:
  enabled: false
jobs:
- yaml/jobs_1.yaml
- yaml/jobs_2.yaml
- yaml/jobs_3.yaml
- yaml/jobs_4.yaml
