  runtime:
    random_seed: 1
    opt_study_count: 2
    opt_n_trial: 2
    transformations_target: diff
    transformations_exog: diff

  training:
    input_size: 96
    batch_size: 16
    valid_batch_size: 4
    windows_batch_size: 32
    inference_windows_batch_size: 32
    max_steps: 1600
    val_size: 16
    scaler_type: standard
    val_check_steps: 8
    min_steps_before_early_stop: 400
    model_step_size: 8
    early_stop_patience_steps: 20
    loss: exloss
    loss_params:
      up_th: 0.85
      down_th: 0.10
      lamda_underestimate: 4.0
      lamda_overestimate: 1.0
      lamda: 1.0
    optimizer:
      name: adamw
      kwargs: {}
    lr_scheduler:
      name: ReduceLROnPlateau
      max_lr: 0.0003
      mode: min
      factor: 0.5
      patience: 2
      threshold: 0.001
      threshold_mode: rel
      cooldown: 0
      min_lr: 0.0
      eps: 0.000001

  cv:
    gap: 0
    horizon: 4
    step_size: 4
    n_windows: 4
    max_train_size: null
    overlap_eval_policy: by_cutoff_mean

  scheduler:
    gpu_ids: [0, 1]
    max_concurrent_jobs: 2
    worker_devices: 1