from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Any

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULT_MDS = (
    REPO_ROOT / "runs/raw_feature_set_aaforecast_wti/F1/result.md",
    REPO_ROOT / "runs/raw_feature_set_aaforecast_wti/brent/F1/result.md",
    REPO_ROOT / "runs/raw_feature_set_aaforecast_wti/brent/dubai/F1/result.md",
)
DEFAULT_OUTPUT_DIR = (
    REPO_ROOT / "runs/analysis/feature_set_aaforecast_fold_mape_compare/F1"
)
TARGET_TO_COMMODITY = {
    "Com_CrudeOil": "WTI",
    "Com_BrentCrudeOil": "Brent",
    "Com_DubaiOil": "Dubai",
}
RESULT_SECTION_HEADING = "## 04-04. Fold별 MAPE 요약"
FAMILY_SORT_ORDER = {"baseline": 0, "AAForecast": 1}
BACKBONE_SORT_ORDER = {"gru": 0, "informer": 1, "timexer": 2}
COMMODITY_SORT_ORDER = {"WTI": 0, "Brent": 1, "Dubai": 2}
MEAN_TOLERANCE_PCT = 0.06


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Compare retrieval on/off fold MAPE across WTI/Brent/Dubai feature-set "
            "AAForecast result.md reports."
        )
    )
    parser.add_argument(
        "--result-md",
        action="append",
        dest="result_mds",
        help=(
            "Path to a result.md file generated by "
            "scripts/feature_set_aaforecast_postprocess.py. "
            "Repeat to provide multiple commodities."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Directory to write CSV/markdown outputs (default: {DEFAULT_OUTPUT_DIR})",
    )
    return parser


def _render_markdown_table(headers: list[str], rows: list[list[Any]]) -> str:
    rendered_rows = [["" if value is None else str(value) for value in row] for row in rows]
    widths = [len(str(header)) for header in headers]
    for row in rendered_rows:
        for idx, value in enumerate(row):
            widths[idx] = max(widths[idx], len(value))

    def render_row(values: list[str]) -> str:
        padded = [value.ljust(widths[idx]) for idx, value in enumerate(values)]
        return "| " + " | ".join(padded) + " |"

    separator = "| " + " | ".join("-" * width for width in widths) + " |"
    return "\n".join([render_row([str(h) for h in headers]), separator, *[render_row(r) for r in rendered_rows]])


def _extract_target(text: str) -> str:
    match = re.search(r"^\- \*\*예측 타깃:\*\*\s+(.+?)\s*$", text, flags=re.MULTILINE)
    if match is None:
        raise ValueError("Could not find '**예측 타깃:**' line in result.md")
    return match.group(1).strip()



def _commodity_from_target(target: str) -> str:
    try:
        return TARGET_TO_COMMODITY[target]
    except KeyError as exc:
        raise ValueError(f"Unsupported target '{target}' in result.md") from exc



def _extract_markdown_table_lines(text: str, heading: str) -> list[str]:
    lines = text.splitlines()
    start_idx: int | None = None
    for idx, line in enumerate(lines):
        if line.strip() == heading:
            start_idx = idx + 1
            break
    if start_idx is None:
        raise ValueError(f"Could not find section heading '{heading}' in result.md")

    table_lines: list[str] = []
    collecting = False
    for line in lines[start_idx:]:
        stripped = line.strip()
        if stripped.startswith("|"):
            collecting = True
            table_lines.append(stripped)
            continue
        if collecting:
            break
    if len(table_lines) < 3:
        raise ValueError(f"Section '{heading}' did not contain a markdown table")
    return table_lines



def _parse_markdown_table(table_lines: list[str]) -> pd.DataFrame:
    rows = list(csv.reader(table_lines, delimiter="|"))
    normalized = [[cell.strip() for cell in row[1:-1]] for row in rows]
    header = normalized[0]
    if not header:
        raise ValueError("Markdown table header was empty")
    body = normalized[2:]
    if not body:
        raise ValueError("Markdown table body was empty")
    for row in body:
        if len(row) != len(header):
            raise ValueError("Markdown table row width mismatch")
    return pd.DataFrame(body, columns=header)



def _parse_percent(value: str) -> float:
    text = str(value).strip()
    if not text.endswith("%"):
        raise ValueError(f"Expected percent value, got '{value}'")
    return float(text[:-1])



def _normalize_family(raw_family: str) -> tuple[str, bool]:
    text = raw_family.strip()
    if text.startswith("baseline"):
        return "baseline", "derived non-ret" in text
    if text.startswith("AAForecast"):
        return "AAForecast", "derived non-ret" in text
    raise ValueError(f"Unsupported family label '{raw_family}'")



def _validate_required_columns(frame: pd.DataFrame) -> list[str]:
    required = {"실험군", "Backbone", "Retrieval", "Mean MAPE"}
    missing = required.difference(frame.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")
    fold_columns = [column for column in frame.columns if column.startswith("Fold ")]
    if not fold_columns:
        raise ValueError("Fold MAPE table did not contain any 'Fold N' columns")
    fold_columns = sorted(fold_columns, key=lambda value: int(value.split()[1]))
    return fold_columns



def parse_result_markdown(result_md_path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    text = result_md_path.read_text(encoding="utf-8")
    commodity = _commodity_from_target(_extract_target(text))
    table_frame = _parse_markdown_table(_extract_markdown_table_lines(text, RESULT_SECTION_HEADING))
    fold_columns = _validate_required_columns(table_frame)

    condition_rows: list[dict[str, Any]] = []
    tidy_rows: list[dict[str, Any]] = []

    for _, row in table_frame.iterrows():
        family, derived_nonret = _normalize_family(str(row["실험군"]))
        retrieval = str(row["Retrieval"]).strip().lower()
        if retrieval not in {"on", "off"}:
            raise ValueError(f"Unsupported retrieval label '{row['Retrieval']}'")
        if derived_nonret and retrieval != "off":
            raise ValueError(
                "Rows labeled '(derived non-ret)' must be paired with Retrieval=off"
            )
        backbone = str(row["Backbone"]).strip()
        backbone_key = backbone.lower()
        if backbone_key not in BACKBONE_SORT_ORDER:
            raise ValueError(f"Unsupported backbone label '{backbone}'")

        fold_values = [_parse_percent(str(row[column])) for column in fold_columns]
        reported_mean_mape_pct = _parse_percent(str(row["Mean MAPE"]))
        computed_mean_mape_pct = sum(fold_values) / len(fold_values)
        if abs(computed_mean_mape_pct - reported_mean_mape_pct) > MEAN_TOLERANCE_PCT:
            raise ValueError(
                f"Reported Mean MAPE mismatch for {commodity}/{family}/{backbone}/{retrieval}: "
                f"reported={reported_mean_mape_pct:.4f}, computed={computed_mean_mape_pct:.4f}"
            )

        condition_rows.append(
            {
                "commodity": commodity,
                "family": family,
                "raw_family": str(row["실험군"]).strip(),
                "derived_nonret": derived_nonret,
                "backbone": backbone,
                "backbone_key": backbone_key,
                "retrieval": retrieval,
                "fold_count": len(fold_columns),
                "reported_mean_mape_pct": reported_mean_mape_pct,
                "computed_mean_mape_pct": computed_mean_mape_pct,
                "source_result_md": str(result_md_path),
            }
        )
        for fold_idx, fold_value in enumerate(fold_values):
            tidy_rows.append(
                {
                    "commodity": commodity,
                    "family": family,
                    "raw_family": str(row["실험군"]).strip(),
                    "derived_nonret": derived_nonret,
                    "backbone": backbone,
                    "backbone_key": backbone_key,
                    "retrieval": retrieval,
                    "fold_idx": fold_idx,
                    "mape_pct": fold_value,
                    "reported_mean_mape_pct": reported_mean_mape_pct,
                    "source_result_md": str(result_md_path),
                }
            )

    condition_frame = pd.DataFrame(condition_rows)
    tidy_frame = pd.DataFrame(tidy_rows)
    _validate_condition_frame(condition_frame)
    return condition_frame, tidy_frame



def _validate_condition_frame(condition_frame: pd.DataFrame) -> None:
    commodity = str(condition_frame["commodity"].iloc[0])
    if len(condition_frame) != 12:
        raise ValueError(f"Expected 12 conditions for {commodity}, found {len(condition_frame)}")

    pair_counts = (
        condition_frame.groupby(["family", "backbone_key"])["retrieval"].nunique().sort_index()
    )
    if len(pair_counts) != 6 or (pair_counts != 2).any():
        raise ValueError(f"Expected 6 on/off pairs for {commodity}, found {pair_counts.to_dict()}")

    fold_counts = condition_frame["fold_count"].unique().tolist()
    if len(fold_counts) != 1:
        raise ValueError(f"Expected a single fold_count for {commodity}, found {fold_counts}")



def _sort_frame(frame: pd.DataFrame, *, include_fold_idx: bool = False) -> pd.DataFrame:
    working = frame.copy()
    working["_commodity_order"] = working["commodity"].map(COMMODITY_SORT_ORDER)
    working["_family_order"] = working["family"].map(FAMILY_SORT_ORDER)
    working["_backbone_order"] = working["backbone_key"].map(BACKBONE_SORT_ORDER)
    order_columns = [
        "_commodity_order",
        "_family_order",
        "_backbone_order",
    ]
    if "retrieval" in working.columns:
        working["_retrieval_order"] = working["retrieval"].map({"off": 0, "on": 1})
        order_columns.append("_retrieval_order")
    if include_fold_idx:
        order_columns.append("fold_idx")
    drop_columns = [column for column in ["_commodity_order", "_family_order", "_backbone_order", "_retrieval_order"] if column in working.columns]
    working = working.sort_values(order_columns, kind="stable").drop(columns=drop_columns)
    return working.reset_index(drop=True)



def build_outputs(result_md_paths: list[Path], output_dir: Path) -> dict[str, Path]:
    if not result_md_paths:
        raise ValueError("At least one --result-md path is required")

    condition_frames: list[pd.DataFrame] = []
    tidy_frames: list[pd.DataFrame] = []
    for path in result_md_paths:
        if not path.exists():
            raise FileNotFoundError(f"Missing result.md: {path}")
        condition_frame, tidy_frame = parse_result_markdown(path)
        condition_frames.append(condition_frame)
        tidy_frames.append(tidy_frame)

    all_conditions = _sort_frame(pd.concat(condition_frames, ignore_index=True))
    all_tidy = _sort_frame(pd.concat(tidy_frames, ignore_index=True), include_fold_idx=True)

    summary = _build_retrieval_summary(all_conditions)
    fold_delta = _build_fold_delta_summary(all_tidy)
    report_path_map = _write_outputs(
        output_dir=output_dir,
        all_conditions=all_conditions,
        all_tidy=all_tidy,
        summary=summary,
        fold_delta=fold_delta,
        result_md_paths=result_md_paths,
    )
    return report_path_map



def _build_retrieval_summary(all_conditions: pd.DataFrame) -> pd.DataFrame:
    pivot = (
        all_conditions.pivot_table(
            index=["commodity", "family", "backbone", "backbone_key"],
            columns="retrieval",
            values="reported_mean_mape_pct",
            aggfunc="first",
        )
        .reset_index()
        .rename_axis(None, axis=1)
    )
    expected_columns = {"off", "on"}
    if not expected_columns.issubset(pivot.columns):
        raise ValueError("Could not build retrieval summary because on/off columns were incomplete")
    pivot["delta_mape_pct"] = pivot["on"] - pivot["off"]
    pivot["improved_with_retrieval"] = pivot["delta_mape_pct"] < 0
    pivot = pivot.rename(
        columns={
            "off": "off_mean_mape_pct",
            "on": "on_mean_mape_pct",
        }
    )
    return _sort_frame(pivot)



def _build_fold_delta_summary(all_tidy: pd.DataFrame) -> pd.DataFrame:
    pivot = (
        all_tidy.pivot_table(
            index=["commodity", "family", "backbone", "backbone_key", "fold_idx"],
            columns="retrieval",
            values="mape_pct",
            aggfunc="first",
        )
        .reset_index()
        .rename_axis(None, axis=1)
    )
    expected_columns = {"off", "on"}
    if not expected_columns.issubset(pivot.columns):
        raise ValueError("Could not build fold delta summary because on/off columns were incomplete")
    pivot["delta_mape_pct"] = pivot["on"] - pivot["off"]
    pivot["improved_with_retrieval"] = pivot["delta_mape_pct"] < 0
    pivot["worsened_with_retrieval"] = pivot["delta_mape_pct"] > 0
    pivot["unchanged_with_retrieval"] = pivot["delta_mape_pct"] == 0

    grouped = (
        pivot.groupby(["commodity", "family", "backbone", "backbone_key"], as_index=False)
        .agg(
            improved_fold_count=("improved_with_retrieval", "sum"),
            worsened_fold_count=("worsened_with_retrieval", "sum"),
            unchanged_fold_count=("unchanged_with_retrieval", "sum"),
            mean_delta_mape_pct=("delta_mape_pct", "mean"),
        )
    )
    return _sort_frame(grouped)



def _write_outputs(
    *,
    output_dir: Path,
    all_conditions: pd.DataFrame,
    all_tidy: pd.DataFrame,
    summary: pd.DataFrame,
    fold_delta: pd.DataFrame,
    result_md_paths: list[Path],
) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    path_map: dict[str, Path] = {}

    all_conditions_path = output_dir / "all_conditions_summary.csv"
    all_conditions.to_csv(all_conditions_path, index=False)
    path_map["all_conditions_summary"] = all_conditions_path

    all_tidy_path = output_dir / "all_fold_mape_tidy.csv"
    all_tidy.to_csv(all_tidy_path, index=False)
    path_map["all_fold_mape_tidy"] = all_tidy_path

    summary_path = output_dir / "all_retrieval_summary.csv"
    summary.to_csv(summary_path, index=False)
    path_map["all_retrieval_summary"] = summary_path

    fold_delta_path = output_dir / "all_fold_delta_summary.csv"
    fold_delta.to_csv(fold_delta_path, index=False)
    path_map["all_fold_delta_summary"] = fold_delta_path

    for commodity, commodity_frame in all_tidy.groupby("commodity", sort=False):
        commodity_path = output_dir / f"{commodity.lower()}_fold_mape_tidy.csv"
        commodity_frame.to_csv(commodity_path, index=False)
        path_map[f"{commodity.lower()}_fold_mape_tidy"] = commodity_path

    for commodity, commodity_frame in summary.groupby("commodity", sort=False):
        commodity_path = output_dir / f"{commodity.lower()}_retrieval_summary.csv"
        commodity_frame.to_csv(commodity_path, index=False)
        path_map[f"{commodity.lower()}_retrieval_summary"] = commodity_path

    report_path = output_dir / "report.md"
    report_path.write_text(
        _build_report(
            all_conditions=all_conditions,
            summary=summary,
            fold_delta=fold_delta,
            result_md_paths=result_md_paths,
        ),
        encoding="utf-8",
    )
    path_map["report"] = report_path
    return path_map



def _format_pct(value: float) -> str:
    return f"{value:.2f}%"



def _format_delta_pct(value: float) -> str:
    sign = "+" if value > 0 else ""
    return f"{sign}{value:.2f}%p"



def _build_report(
    *,
    all_conditions: pd.DataFrame,
    summary: pd.DataFrame,
    fold_delta: pd.DataFrame,
    result_md_paths: list[Path],
) -> str:
    best_rows = (
        all_conditions.sort_values(["commodity", "reported_mean_mape_pct", "family", "backbone_key"])\
        .groupby("commodity", as_index=False)
        .first()
    )
    best_table = _render_markdown_table(
        ["Commodity", "Family", "Backbone", "Retrieval", "Mean MAPE"],
        [
            [
                row["commodity"],
                row["family"],
                row["backbone"],
                row["retrieval"],
                _format_pct(float(row["reported_mean_mape_pct"])),
            ]
            for _, row in best_rows.iterrows()
        ],
    )

    summary_table = _render_markdown_table(
        [
            "Commodity",
            "Family",
            "Backbone",
            "off Mean MAPE",
            "on Mean MAPE",
            "Δ MAPE",
            "Improved",
        ],
        [
            [
                row["commodity"],
                row["family"],
                row["backbone"],
                _format_pct(float(row["off_mean_mape_pct"])),
                _format_pct(float(row["on_mean_mape_pct"])),
                _format_delta_pct(float(row["delta_mape_pct"])),
                "yes" if bool(row["improved_with_retrieval"]) else "no",
            ]
            for _, row in summary.iterrows()
        ],
    )

    fold_delta_table = _render_markdown_table(
        [
            "Commodity",
            "Family",
            "Backbone",
            "Improved folds",
            "Worsened folds",
            "Unchanged folds",
            "Mean Δ MAPE",
        ],
        [
            [
                row["commodity"],
                row["family"],
                row["backbone"],
                int(row["improved_fold_count"]),
                int(row["worsened_fold_count"]),
                int(row["unchanged_fold_count"]),
                _format_delta_pct(float(row["mean_delta_mape_pct"])),
            ]
            for _, row in fold_delta.iterrows()
        ],
    )

    commodity_rollup = (
        summary.groupby("commodity", as_index=False)
        .agg(
            improved_backbone_count=("improved_with_retrieval", "sum"),
            total_backbone_count=("improved_with_retrieval", "size"),
            mean_delta_mape_pct=("delta_mape_pct", "mean"),
        )
        .sort_values("commodity", key=lambda s: s.map(COMMODITY_SORT_ORDER))
        .reset_index(drop=True)
    )
    overall_table = _render_markdown_table(
        ["Commodity", "Improved backbones", "Total backbones", "Mean Δ MAPE"],
        [
            [
                row["commodity"],
                int(row["improved_backbone_count"]),
                int(row["total_backbone_count"]),
                _format_delta_pct(float(row["mean_delta_mape_pct"])),
            ]
            for _, row in commodity_rollup.iterrows()
        ],
    )

    source_lines = [f"- `{path}`" for path in result_md_paths]

    return "\n".join(
        [
            "# Feature-set AAForecast retrieval on/off fold MAPE comparison",
            "",
            "## Sources",
            *source_lines,
            "",
            "## Best mean-MAPE condition by commodity",
            best_table,
            "",
            "## Retrieval on/off mean MAPE summary",
            summary_table,
            "",
            "## Retrieval on/off fold-win summary",
            fold_delta_table,
            "",
            "## Commodity-level rollup",
            overall_table,
            "",
        ]
    )



def main(argv: list[str] | None = None) -> int:
    parser = _build_arg_parser()
    args = parser.parse_args(argv)
    result_md_paths = [Path(path).resolve() for path in (args.result_mds or DEFAULT_RESULT_MDS)]
    output_dir = args.output_dir.resolve()
    path_map = build_outputs(result_md_paths, output_dir)
    for key, path in sorted(path_map.items()):
        print(f"{key}={path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
