runtime:
  random_seed: 1
training:
  batch_size: 32
  valid_batch_size: 64
  windows_batch_size: 1024
  inference_windows_batch_size: 1024
  max_steps: 1000
  val_size: 8
  model_step_size: 8
cv:
  gap: 0
  overlap_eval_policy: by_cutoff_mean
scheduler:
  max_concurrent_jobs: 2
  worker_devices: 1
family_defaults:
  feature_set:
    training:
      input_size: 64
      learning_rate: 0.001
      val_check_steps: 50
      early_stop_patience_steps: 5
      loss: mse
    cv:
      horizon: 8
      step_size: 8
      n_windows: 12
      max_train_size: null
    scheduler:
      gpu_ids: [0, 1]
    files:
      brentoil-case3.yaml:
        scheduler:
          gpu_ids: [1]
  feature_set_bs:
    training:
      input_size: 64
      learning_rate: 0.001
      val_check_steps: 50
      early_stop_patience_steps: 5
      loss: mse
    cv:
      horizon: 8
      step_size: 8
      n_windows: 12
      max_train_size: null
    scheduler:
      gpu_ids: [0, 1]
    files:
      brentoil-case3.yaml:
        scheduler:
          gpu_ids: [1]
  feature_set_bs_diff:
    training:
      input_size: 64
      learning_rate: 0.001
      val_check_steps: 50
      early_stop_patience_steps: 5
      loss: mse
    cv:
      horizon: 8
      step_size: 8
      n_windows: 12
      max_train_size: null
    scheduler:
      gpu_ids: [0, 1]
    files:
      brentoil-case3.yaml:
        scheduler:
          gpu_ids: [1]
  feature_set_bs_exloss:
    training:
      input_size: 64
      learning_rate: 0.001
      val_check_steps: 50
      early_stop_patience_steps: 5
      loss: exloss
    cv:
      horizon: 8
      step_size: 8
      n_windows: 12
      max_train_size: null
    scheduler:
      gpu_ids: [0, 1]
    files:
      brentoil-case3.yaml:
        scheduler:
          gpu_ids: [1]
  feature_set_bs_preforcast:
    training:
      input_size: 64
      learning_rate: 0.001
      val_check_steps: 50
      early_stop_patience_steps: 5
      loss: mse
    cv:
      horizon: 8
      step_size: 8
      n_windows: 12
      max_train_size: null
    scheduler:
      gpu_ids: [0, 1]
    files:
      brentoil-case3.yaml:
        scheduler:
          gpu_ids: [1]
  feature_set_HPT_n100_bs:
    training:
      input_size: 64
      learning_rate: 0.001
      val_check_steps: 50
      early_stop_patience_steps: 3
      loss: mse
    cv:
      horizon: 8
      step_size: 8
      n_windows: 5
      max_train_size: null
    scheduler:
      gpu_ids: [0, 1]
