task:
  name: brentoil_case3_HPO
dataset:
  path: data/df.csv
  target_col: Com_BrentCrudeOil
  dt_col: dt
  hist_exog_cols:
  - Com_Gasoline
  - Com_BloombergCommodity_BCOM
  - Com_LME_Ni_Cash
  - Com_Coal
  - Com_LME_Al_Cash
  - Bonds_KOR_10Y
  - Com_LMEX
  - Com_LME_Ni_Inv
  - BS_Core_Index_A
  - BS_Core_Index_B
  - BS_Core_Index_C
  - BS_Core_Index_Integrated
  futr_exog_cols: []
  static_exog_cols: []
runtime:
  random_seed: 1
  opt_n_trial: 100
training:
  train_protocol: expanding_window_tscv
  season_length: 52
  batch_size: 32
  valid_batch_size: 32
  windows_batch_size: 1024
  inference_windows_batch_size: 1024
  max_steps: 1000
  val_check_steps: 50
  val_size: 8
  early_stop_patience_steps: 3
  loss: mse
  dataloader_kwargs:
    num_workers: 2
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 2
cv:
  horizon: 8
  step_size: 8
  n_windows: 5
  gap: 0
  max_train_size: null
  overlap_eval_policy: by_cutoff_mean
scheduler:
  gpu_ids:
  - 0
  - 1
  max_concurrent_jobs: 2
  worker_devices: 1
  parallelize_single_job_tuning: true
residual:
  enabled: false
jobs:
- model: PatchTST
  params: {}
- model: TSMixerx
  params: {}
- model: Naive
  params: {}
- model: iTransformer
  params: {}
- model: LSTM
  params: {}
